# Generated by Django 5.2.13 on 2026-04-26 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exigence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur', models.CharField(max_length=255)),
                ('cible', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_structure', models.CharField(max_length=200)),
                ('type_structure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('metier', 'Metier'), ('pilote', 'Pilote'), ('auditeur_interne', 'Auditeur Interne'), ('auditeur_externe', 'Auditeur Externe')], default='metier', max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('objectif', models.TextField(blank=True)),
                ('etat_pr', models.CharField(default='brouillon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.structure')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('statut', models.CharField(default='en_cours', max_length=20)),
                ('priorite', models.CharField(blank=True, max_length=20)),
                ('delai', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_actions', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('gravite', models.CharField(max_length=20)),
                ('etat_nc', models.CharField(default='ouverte', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformites', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='Moyens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('processus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moyens', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='KPIProcessus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(max_length=50)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kpi')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='InfoDocumentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_document', models.CharField(max_length=255)),
                ('lien', models.URLField(blank=True)),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='ExigenceProcessus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exigence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exigence')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exigences', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='Contrainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraintes', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audit', models.DateField()),
                ('etat_audit', models.CharField(default='planifie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='api.processus')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='api.processus')),
            ],
        ),
    ]
