# Generated by Django 5.2.13 on 2026-05-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigenceprocessus',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
