# Generated by Django 5.2.13 on 2026-05-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exigenceprocessus_is_satisfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exigence',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='exigence',
            name='description',
        ),
        migrations.AddField(
            model_name='exigence',
            name='code',
            field=models.CharField(default='ISO-UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exigence',
            name='titre',
            field=models.CharField(default='ISO-UNKNOWN', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExigenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('exigence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.exigence')),
            ],
        ),
        migrations.CreateModel(
            name='ExigenceValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exigenceitem')),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processus')),
            ],
        ),
        migrations.DeleteModel(
            name='ExigenceProcessus',
        ),
    ]
