# Generated by Django 5.2.13 on 2026-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_exigence_chapitre_remove_exigence_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processus',
            name='type_processus',
            field=models.CharField(default='Support', max_length=50),
        ),
        migrations.AddField(
            model_name='processus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
