# Generated by Django 5.2.13 on 2026-05-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_processus_type_processus_processus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='clause',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='audit',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audit',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planaction',
            name='clause',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
