# Generated by Django 5.2.13 on 2026-05-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_audit_clause_audit_date_debut_audit_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date_audit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='processus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.processus'),
        ),
    ]
