# Generated by Django 5.2.13 on 2026-05-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_audit_date_audit_alter_audit_processus'),
    ]

    operations = [
        migrations.AddField(
            model_name='processus',
            name='score_iso',
            field=models.IntegerField(default=0),
        ),
    ]
